### ISSUE TITLE
Print order entirely broken

### ISSUE THREAD

**Issue by curlyjason** [curlyjason/AMPfg10#1]
Lots of missing data elements (details below and an issue for all related problems at #4)

**Comment by dreamingmind** [comment]
The failure can be found through the print link on any order on the status page:

<img width="349" alt="Screen Shot 2019-03-30 at 3 53 06 PM" src="https://user-images.githubusercontent.com/1307216/55282594-29eec800-5304-11e9-8a3d-39bca6c852ae.png">

And is throwing errors like this:

<img width="1173" alt="Screen Shot 2019-03-30 at 3 54 08 PM" src="https://user-images.githubusercontent.com/1307216/55282597-383ce400-5304-11e9-97fd-d8a375dfa8d5.png">

**Comment by dreamingmind** [comment]
The apparent reason for the empty $order array that is triggering these errors is The value of $id at this point. No table has an id with a .pdf extension.

So, OrdersController::printOrder() line 229 might be the culprit.

**Comment by dreamingmind** [comment]
OrdersController uses a conditional to test the setting of `$this->request->params['ext']` but that node is not set. 

Searching /app for `params['ext']` reveals MANY tests of this node and no setters that I could find. This must be a change in the `Requst` object and will cause breaks all over the system.

If the conditional passed, the .pdf would have been removed from the id and all would be well

**Comment by dreamingmind** [comment]
I haven't been able to find the exact change to `Request` that caused this, but here's some info.

In 2.4 the `Request::param($name) method was added to eliminate the need to test the array node before using the value. So, we should be able to leverage this new method to fix all the conditional.

There are other details to be aware of though. Our original code in 2.3 had a param array like this at `OrdersContoller::printOrder($id)`:

<img width="535" alt="Screen Shot 2019-03-30 at 5 05 11 PM" src="https://user-images.githubusercontent.com/1307216/55283052-b9997400-530e-11e9-98a1-8e50bab787f5.png">

The current 2.10 array at this point is:

<img width="568" alt="Screen Shot 2019-03-30 at 5 05 28 PM" src="https://user-images.githubusercontent.com/1307216/55283067-02e9c380-530f-11e9-82d1-2c2d28d84f22.png">

I don't know why the `pass` value retained its extension in the second version. It's highly likely that this is core behavior and not something we've done.

**Comment by dreamingmind** [comment]
The initial raft of errors has been taken care of. But the method is now failing in a silent way. Previously it at least printed an empty Order template with the error messages. Now it makes a cake page with and sql query report at the bottom of the page
